(*<scc.pas>
 * Library for SCC soundchip handling.
 * Thanks to BIFI's website at http://bifi.msxnet.org/msxnet//tech/scc
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This module depends on folowing include files (respect the order):
 * - /system/types.pas;
 * - /sndchips/sndchips.pas;
 *)

const
       { SCC related constants }
       ctSCCRegCounter                     = $7F;   { SCC register counter   }
       ctSCCPortCounter                    = $03;   { SCC port counter       }

       { SCC registers base addresses definitions }
       ctSCCWaveformBaseAddress  : integer = $9800; { Waveform base address  }
       ctSCCFrequencyBaseAddress : integer = $9880; { Frequency base address }
       ctSCCAmplitudeBaseAddress : integer = $988A; { Amplitude base address }
       ctSCCMixerBaseAddress     : integer = $988F; { Mixer base address     }


(**
  * SCC base address array definition.
  *)
type PSCCBaseAddresses = ^TSCCBaseAddresses;
     TSCCBaseAddresses = array[0..3] of integer;

(**
  * Local module variables.
  *)
var
      __nSCCPrimarySlot,
      __nSCCSecondarySlot : byte;
      __aSCCBaseAddresses : TSCCBaseAddresses;
      __pSCCBaseAddresses : PSCCBaseAddresses;


(**
  * Write data to SCC sound chip using internal variable parameter;
  * @param __nSCCPrimarySlot The SCC primary slot;
  * @param __nSCCSecondarySlot The SCC secondary slot;
  * @param __pSndChipArrayParms The address of an array containing the SCC
  * data like below:
  * item[0] := SCC Port;
  * item[1] := SCC Register;
  * item[2] := SCC Data;
  *)
procedure WriteSCCDirect{( __nSCCPrimarySlot,
                           __nSCCSecondarySlot : Byte;
                           __pSndChipArrayParms : Pointer ) };
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  inline(
          $ED/$5B/__pSndChipArrayParms{        LD DE,(__pSndChipArrayParms)}
          /$1A                        {        LD A,(DE)                   }
          /$6F                        { BASADR LD L,A                      }
          /$26/$00                    {        LD H,00H                    }
          /$29                        {        ADD HL,HL                   }
          /$ED/$4B/__pSCCBaseAddresses{        LD BC,(__pSCCBaseAddresses) }
          /$09                        {        ADD HL,BC                   }
          /$7E                        {        LD A,(HL)                   }
          /$23                        {        INC HL                      }
          /$66                        {        LD H,(HL)                   }
          /$6F                        {        LD L,A                      }
          /$13                        { SELREG INC DE                      }
          /$1A                        {        LD A,(DE)                   }
          /$4F                        {        LD C,A                      }
          /$06/$00                    {        LD B,0                      }
          /$09                        {        ADD HL,BC                   }
          /$13                        {        INC DE                      }
          /$1A                        {        LD A,(DE)                   }
          /$47                        {        LD B,A                      }
          /$EB                        {        EX DE,HL                    }
          /$2A/$FF/$FF                { SAVSLT LD HL,(SEC_SLOT)            }
          /$0E/$A8                    {        LD C,PPI_SSEL               }
          /$F3                        {        DI                          }
          /$ED/$60                    {        IN H,(C)                    }
          /$3A/__nSCCSecondarySlot    {        LD A,(__nSCCSecondarySlot)  }
          /$4F                        {        LD C,A                      }
          /$3A/__nSCCPrimarySlot      {        LD A,(__nSCCPrimarySlot)    }
          /$D3/$A8                    {        OUT (PPI_SSEL),A            }
          /$79                        {        LD A,C                      }
          /$32/$FF/$FF                {        LD (SEC_SLOT),A             }
          /$78                        { WRTREG LD A,B                      }
          /$12                        {        LD (DE),A                   }
          /$7D                        { RESSLT LD A,L                      }
          /$2F                        {        CPL                         }
          /$32/$FF/$FF                {        LD (SEC_SLOT),A             }
          /$7C                        {        LD A,H                      }
          /$FB                        {        EI                          }
          /$D3/$A8                    {        OUT (PPI_SSEL),A            }
                                      {        END                         } );
end;

(**
  * Write data to SCC sound chip.
  * @param nPrimarySlot The SCC primary slot;
  * @param nSecondarySlot The SCC secondary slot;
  * @param nPort The port that register are categorized;
  * @param nRegister The register index to write data;
  * @param nData The data to be written;
  *)
procedure WriteSCC( nPrimarySlot, nSecondarySlot : byte;
                    nPort, nRegister, nData : byte );
var
       aSCCArrayParms : array [0..2] of byte;

begin
  aSCCArrayParms[0] := nPort;
  aSCCArrayParms[1] := nRegister;
  aSCCArrayParms[2] := nData;

  __nSCCPrimarySlot    := nPrimarySlot;
  __nSCCSecondarySlot  := nSecondarySlot;
  __pSndChipArrayParms := Ptr( Addr( aSCCArrayParms[0] ) );

  WriteSCCDirect{( __nSCCPrimarySlot,
                   __nSCCSecondarySlot,
                   __pSndChipArrayParms )};
end;

(**
  * Reset the SCC soundchip.
  * @param nPrimarySlot The SCC primary slot;
  * @param nSecondarySlot The SCC secondary slot;
  *)
procedure ResetSCC( nPrimarySlot, nSecondarySlot : byte );
var
       nPort,
       nRegister      : byte;
       aSCCArrayParms : array [0..2] of byte;

begin
  __nSCCPrimarySlot    := nPrimarySlot;
  __nSCCSecondarySlot  := nSecondarySlot;
  __pSndChipArrayParms := Ptr( Addr( aSCCArrayParms[0] ) );
  aSCCArrayParms[2]    := 0;               { SCC Data }

  inline( $F3 );    { DI }

  for nPort := 0 to ctSCCPortCounter do    { Port }
  begin
    aSCCArrayParms[0] := nPort;

    for nRegister := 0 to ctSCCRegCounter do   { Register }
    begin
      aSCCArrayParms[1] := nRegister;

      WriteSCCDirect{( __nSCCPrimarySlot,
                       __nSCCSecondarySlot,
                       __pSndChipArrayParms )};
    end;
  end;

  inline( $FB );    { EI }
end;

(**
  * Set the base address table for using with SCC Assembly calls.
  *)
procedure InitSCCBaseAddresses;
begin
  __aSCCBaseAddresses[0] := ctSCCWaveformBaseAddress;
  __aSCCBaseAddresses[1] := ctSCCFrequencyBaseAddress;
  __aSCCBaseAddresses[2] := ctSCCAmplitudeBaseAddress;
  __aSCCBaseAddresses[3] := ctSCCMixerBaseAddress;
  __pSCCBaseAddresses    := Ptr( Addr( __aSCCBaseAddresses ) );
end;
