(*<AY8910.pas>
 * Library for the AY8910 soundchip handling.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This module depends on folowing include files (respect the order):
 * - /system/types.pas;
 * - /sndchips/sndchips.pas;
 *)

const
         { AY8910 related constants }
         ctPortAY38910RegisterWrite : byte = $A0; { AY-3-8910 reg. write port }
         ctPortAY38910DataWrite     : byte = $A1; { AY-3-8910 val. write port }
         ctPortAY38910DataRead      : byte = $A2; { AY-3-8910 val. read port  }
         ctAY8910RegCount           : byte = $0F; { AY-3-8910 16 registers    }


(**
  * Write data to AY8910 sound chip using internal variable parameter;
  * @param __pSndChipArrayParms The AY8910 array address containing the
  * parameters like described below:
  * item[0] := AY8910 Address Register;
  * item[1] := AY8910 Data Register;
  *)
procedure WriteAY8910Direct{( __pSndChipArrayParms : Pointer )};
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  inline(
          $2A/__pSndChipArrayParms {  LD HL,(__pSndChipArrayParms) }
          /$0E/$A0                 {  LD C,AY8910REGWRITE          }
          /$ED/$A3                 {  OUTI                         }
          /$0C                     {  INC C                        }
          /$ED/$A3                 {  OUTI                         } );
end;

(**
  * Write data to the AY8910 sound chip. This is a wrapper method to the
  * @see WriteAY8910Direct procedure;
  * @param nRegister The register to write data;
  * @param nData The data to be written;
  *)
procedure WriteAY8910( nRegister, nData : byte );
var
         aAY8910ArrayParms : array[0..1] of byte;

begin
  aAY8910ArrayParms[0] := nRegister;
  aAY8910ArrayParms[1] := nData;

  __pSndChipArrayParms := Ptr( Addr( aAY8910ArrayParms ) );
  WriteAY8910Direct{( __pSndChipArrayParms )};
end;

(**
  * Reset the AY8910 sound chip.
  *)
procedure ResetAY8910;
var
         aAY8910ArrayParms : array[0..1] of byte;
         nRegister         : byte;

begin
  aAY8910ArrayParms[0] := nRegister;
  aAY8910ArrayParms[1] := 0;
  __pSndChipArrayParms := Ptr( Addr( aAY8910ArrayParms ) );

  for nRegister := 0 to ctAY8910RegCount do
  begin
    aAY8910ArrayParms[0] := nRegister;

    WriteAY8910Direct{( __pSndChipArrayParms )};
    Delay( ctSndChipResetDelay );
  end;
end;
