(*<longjmp.pas>
 * Long jump implementation for Turbo Pascal 3.
 * Unfortunately this feature doesn't exist in TP3 core language.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This source file depends on following include files (respect the order):
 * -
 *)


(**
  * Set the jump address for long jumps;
  * @param nJmpAddr The returned long jump address;
  *)
procedure SetJmp( var nJmpAddr : integer );
var
        nAddr : integer;

begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   * Source code: asm\system\setjmp.asm
   *)
   inline(
           $E1         {  POP  HL           }
           /$D1        {  POP  DE           }
           /$22/nAddr  {  LD   (nAddr),HL   }
           /$D5        {  PUSH DE           }
           /$E5        {  PUSH HL           } );

  nJmpAddr := nAddr;
end;

(**
  * Perform a Long Jump address for a given address;
  * @param nJmpAddr The address to perform a long jump;
  *)
procedure LongJmp( nJmpAddr : integer);
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   * Source code: asm\system\longjmp.asm
   *)
  inline(
          $2A/nJmpAddr  { LD HL,(nJmpAddr)     }
          /$E9          { JP (HL)              } );
end;
