(*<ym2413.pas>
 * Library for the YM2413 soundchip handling.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This module depends on folowing include files (respect the order):
 * - /system/types.pas;
 * - /sndchips/sndchips.pas;
 *)

const
       { YM2413 related constants }
       ctPortYM2413Index          : byte = $7C;   { YM2413 index write port }
       ctPortYM2413Data           : byte = $7D;   { YM2413 data I/O }
       ctYM2413RegIdxCount        : byte = $26;   { YM2413 registers count }
       (*ctFMIdentification      : Integer = $401C; { OPLL string ident. addr. }*)


(**
  * Write data to YM2413 sound chip using internal variable parameter;
  * @param __pSndChipArrayParms The AY2413 array address containing the
  * parameters like described below:
  * item[0] := YM2413 Index Register;
  * item[1] := YM2413 Data Register;
  *)
procedure WriteYM2413Direct{( __pSndChipArrayParms : Pointer )};
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   * Source code: asm\sndchip\ym2413.asm
   *)
  inline(
          $2A/__pSndChipArrayParms { LD HL,(__pSndChipArrayParm)  }
          /$0E/$7C                 { LD C,YM2413INDEX             }
          /$ED/$A3                 { OUTI                         }
          /$DD/$E5                 { PUSH IX                      }
          /$DD/$E1                 { POP IX                       }
          /$0C                     { INC C                        }
          /$ED/$A3                 { OUTI                         } );
end;

(**
  * Write data to YM2413 sound chip. This is a wrapper function to the
  * @see WriteYM2413Direct procedure.
  * @param nIndex The register index to write data;
  * @param nData The data to be written;
  *)
procedure WriteYM2413( nIndex, nData : byte );
var
         aYM2413ArrayParms : array[0..1] of byte;

begin
  aYM2413ArrayParms[0] := nIndex;
  aYM2413ArrayParms[1] := nData;
  __pSndChipArrayParms := Ptr( Addr( aYM2413ArrayParms ) );

  WriteYM2413Direct{( __pSndChipArrayParms )};
end;

(**
  * Reset the YM2413 sound chip.
  *)
procedure ResetYM2413;
var
         aYM2413ArrayParms : array[0..1] of byte;
         nIndex            : byte;

begin
  aYM2413ArrayParms[0] := nIndex;
  aYM2413ArrayParms[1] := 0;
  __pSndChipArrayParms := Ptr( Addr( aYM2413ArrayParms ) );

  for nIndex := 0 to ctYM2413RegIdxCount do
  begin
    aYM2413ArrayParms[0] := nIndex;

    WriteYM2413Direct{( __pSndChipArrayParms )};
    Delay( ctSndChipResetDelay );
  end;
end;
