(*<pointer.pas>
 * Pointer functions to make Turbo Pascal 3 more flexible with
 * modern pointer operations, present in newer Delphi releases.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This module depends on folowing include files (respect the order):
 * - /system/types.pas
 *)


(**
  * Increment the pointer address using the units passed by parameter.
  * @param pPointer The pointer that address will be incremented;
  * @param nIncrement The increment to skip to thew new address;
  *)
function IncPtr( pPointer : Pointer; nIncrement : integer ) : TPointer;
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
   (* TODO: REMOVER ANTES DA VERSÃO FINAL - SUBSTITUIR POR PRE-PROCESSING
  inline( $2A/pPointer         { LD  HL,(pPointer)     }
          /$ED/$5B/nIncrement  { LD  DE,(nIncrement)   }
          /$19                 { ADD HL,DE             }
          /$22/pPointer        { LD  (pPointer),HL     } );
  *)
  IncPtr := pPointer;
end;

(**
  * Helper function to make TP3 and 3.3f pointer operations more abstract
  * enabling multi-platform code exchangeable with newer pascal implementaion
  * like FPC compiler.
  * Convert an any type variable to pointer;
  * @param variable Variable to be converted to pointer;
  *)
function ToPointer( var variable ) : TPointer;
var
    pRet   : TPointer;

begin
  (* TODO: PRE-PROCESSING *)
  (* pRet := Ptr( Addr( variable ) ); *)
  pRet := Addr( variable );

  ToPointer := pRet;
end;
