(*<math16.pas>
 * Implement extends math functions for use with 16Bit operands.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This source file depends on following include files (respect the order):
 * -
 *)

(**
  * Return the maximum value of two operands.
  * @param nOp1 The first operand;
  * @param nOp2 The second operand;
  *)
function Max( nOp1, nOp2 : integer ) : integer;
begin
  if( nOp1 > nOp2 )  then
    Max := nOp1
  else
    Max := nOp2;
end;

(**
  * Return the minimum value of two operands.
  * @param nOp1 The first operand;
  * @param nOp2 The second operand;
  *)
function Min( nOp1, nOp2 : integer ) : integer;
begin
  if( nOp1 < nOp2 )  then
    Min := nOp1
  else
    Min := nOp2;
end;

(**
  * Performs an integer division rounding the result as needed;
  * @param nDividend The operation dividend;
  * @param nDivisor The operation divisor;
  *)
function RoundDiv16( nDividend, nDivisor : integer ) : integer;
var
          nResult     : integer;
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  inline(
          $ED/$4B/nDividend     { DIV16:   LD BC,(nDividend)    }
          /$ED/$5B/nDivisor     {          LD DE,(nDivisor)     }
          /$21/$00/$00          {          LD HL,0              }
          /$78                  {          LD A,B               }
          /$06/$08              {          LD B,8               }
          /$17                  { LOOP1:   RLA                  }
          /$ED/$6A              {          ADC HL,HL            }
          /$ED/$52              {          SBC HL,DE            }
          /$30/$01              {          JR NC,NOADD1         }
          /$19                  {          ADD HL,DE            }
          /$10/$F6              { NOADD1:  DJNZ LOOP1           }
          /$47                  {          LD B,A               }
          /$79                  {          LD A,C               }
          /$48                  {          LD C,B               }
          /$06/$08              {          LD B,8               }
          /$17                  { LOOP2:   RLA                  }
          /$ED/$6A              {          ADC HL,HL            }
          /$ED/$52              {          SBC HL,DE            }
          /$30/$01              {          JR NC,NOADD2         }
          /$19                  {          ADD HL,DE            }
          /$10/$F6              { NOADD2:  DJNZ LOOP2           }
          /$17                  {          RLA                  }
          /$2F                  {          CPL                  }
          /$47                  {          LD B,A               }
          /$79                  {          LD A,C               }
          /$48                  {          LD C,B               }
          /$17                  {          RLA                  }
          /$2F                  {          CPL                  }
          /$47                  {          LD B,A               }
          /$29                  { ROUND:   ADD HL,HL            }
          /$ED/$52              {          SBC HL,DE            }
          /$38/$01              {          JR C,ENDP            }
          /$03                  {          INC BC               }
          /$ED/$43/nResult      { ENDP:    LD (nResult),BC      }
                                {          END                  } );

  RoundDiv16 := nResult;
end;

(**
  * Performs an integer division returning the division's remainder;
  * @param nDividend The operation dividend;
  * @param nDivisor The operation divisor;
  * @param nRemainder Reference to operation's remainder;
  *)
function Div16( nDividend,
                nDivisor : integer;
                var nRemainder : integer ) : integer;
var
          nResult,
          nRest      : integer;
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  inline(
          $ED/$4B/nDividend     { DIV16    LD BC,(nDividend)    }
          /$ED/$5B/nDivisor     {          LD DE,(nDivisor)     }
          /$21/$00/$00          {          LD HL,0              }
          /$78                  {          LD A,B               }
          /$06/$08              {          LD B,8               }
          /$17                  { LOOP1    RLA                  }
          /$ED/$6A              {          ADC HL,HL            }
          /$ED/$52              {          SBC HL,DE            }
          /$30/$01              {          JR NC,NOADD1         }
          /$19                  {          ADD HL,DE            }
          /$10/$F6              { NOADD1   DJNZ LOOP1           }
          /$47                  {          LD B,A               }
          /$79                  {          LD A,C               }
          /$48                  {          LD C,B               }
          /$06/$08              {          LD B,8               }
          /$17                  { LOOP2    RLA                  }
          /$ED/$6A              {          ADC HL,HL            }
          /$ED/$52              {          SBC HL,DE            }
          /$30/$01              {          JR NC,NOADD2         }
          /$19                  {          ADD HL,DE            }
          /$10/$F6              { NOADD2   DJNZ LOOP2           }
          /$17                  {          RLA                  }
          /$2F                  {          CPL                  }
          /$47                  {          LD B,A               }
          /$79                  {          LD A,C               }
          /$48                  {          LD C,B               }
          /$17                  {          RLA                  }
          /$2F                  {          CPL                  }
          /$47                  {          LD B,A               }
          /$22/nRest            {          LD (nRest),HL        }
          /$ED/$43/nResult      {          LD (nResult),BC      } );

  nRemainder := nRest;
  Div16 := nResult;
end;
