(*<Y8950.pas>
 * Library for the Y8950 (Philips Music Module) soundchip handling.
 * CopyLeft (c) 1995-2024 by PopolonY2k.
 * CopyLeft (c) since 2024 by Hinotori Team.
 *)

(*
 * This module depends on folowing include files (respect the order):
 * - /system/types.pas;
 * - /sndchips/sndchips.pas;
 *)

const
       { Y8950 related constants }
       (*ctPortY8950RegisterWrite   : Byte = $C0;   { Y8950 reg. write port }*)
       ctPortY8950DataWrite       : byte = $C1;   { Y8950 val. write port }
       ctY8950FMInitialSlotReg    : byte = $20;   { Initial slot register }
       ctY8950FMFinalSlotReg      : byte = $35;   { Final slot register }
       ctY8950FMInitialChannelReg : byte = $C0;   { Initial channel register }
       ctY8950FMFinalChannelReg   : byte = $C8;   { Final channel register }


(**
  * Write data to Y8950 sound chip using internal variable parameter;
  * @param __pSndChipArrayParms The Y8950 array address containing the
  * parameters like described below:
  * item[0] := Y8950 Port Register;
  * item[1] := Y8950 Port Data;
  *)
procedure WriteY8950Direct{( __pSndChipArrayParms : Pointer )};
begin
  (*
   * The ASM routine below is located in the .\ASM\ project folder
   * and was generated by INLASS.
   *)
  inline(
          $2A/__pSndChipArrayParms  { LD HL,(__pSndChipArrayParms) }
          /$0E/$C0                  { LD C,Y8950REGWRITE           }
          /$ED/$A3                  { OUTI                         }
          /$DB/$C4                  { IN A,(Y8950STATUSREG)        }
          /$0C                      { INC C                        }
          /$ED/$A3                  { OUTI                         } );
end;

(**
  * Write data to Y8950 sound chip. This is a wrapper to the @see
  * WriteY8950Direct procedure.
  * @param nRegister The register index to write data;
  * @param nData The data to be written;
  *)
procedure WriteY8950( nRegister, nData : byte );
var
         aY8950ArrayParms : array[0..1] of byte;

begin
  aY8950ArrayParms[0]  := nRegister;
  aY8950ArrayParms[1]  := nData;
  __pSndChipArrayParms := Ptr( Addr( aY8950ArrayParms ) );

  WriteY8950Direct{( __pSndChipArrayParms )};
end;

(**
  * Reset the Y8950 sound chip.
  * Check the chapter 2-5 (Channels and slots) of Yamaha Y8950 Application
  * Manual (MSX-AUDIO)
  *)
procedure ResetY8950;
var
         aY8950ArrayParms : array[0..1] of byte;
         nRegister        : integer;

begin
  aY8950ArrayParms[1]  := 0;
  __pSndChipArrayParms := Ptr( Addr( aY8950ArrayParms ) );

  (* Reset FM slots *)
  for nRegister := ctY8950FMInitialSlotReg to ctY8950FMFinalSlotReg do
  begin
    aY8950ArrayParms[0] := nRegister;
    WriteY8950Direct{( __pSndChipArrayParms )};
    Delay( ctSndChipResetDelay );
  end;

  (* Reset FM Channels *)
  for nRegister := ctY8950FMInitialChannelReg to ctY8950FMFinalChannelReg do
  begin
    aY8950ArrayParms[0] := nRegister;
    WriteY8950Direct{( __pSndChipArrayParms )};
    Delay( ctSndChipResetDelay );
  end;
end;
